=== manusss123/AlmacenBueno/ProyectoPrimeraEVacceso/esquemaMoviles.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0">
    <xsd:element name="Moviles">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element name="Movil" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Procesador" type="xsd:string" />
                            <xsd:element name="Memoria_Ram" type="xsd:string" />
                            <xsd:element name="Memoria_interna" type="xsd:string" />
                            <xsd:element name="Bateria" type="xsd:string" />
                            <xsd:element name="Pantalla" type="xsd:string" />
                            <xsd:element name="Resolucino_Pantalla" type="xsd:string" />
                            <xsd:element name="Camara" type="xsd:string" />
                            <xsd:element name="Precio" type="xsd:string" />
                            

                        </xsd:sequence>
                        <xsd:attribute name="marca" type="xsd:string"/>
                        <xsd:attribute name="modelo" type="xsd:string"/>
                        <xsd:attribute name="fechaSalida" type="xsd:string"/>


                    </xsd:complexType>
                </xsd:element>
            </xsd:choice>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== manusss123/AlmacenBueno/ProyectoPrimeraEVacceso/moviles.xml
<?xml version="1.0" encoding="UTF-8"?>
<Moviles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquemaMoviles.xsd">
    <Movil marca="Aplle" modelo="Iphone X" fechaSalida="2017">
        <Procesador>Apple A11</Procesador>
        <Memoria_Ram>3 GB </Memoria_Ram>
        <Memoria_interna>64/256 GB</Memoria_interna>
        <Bateria>2.716 mAh</Bateria>
        <Pantalla>5,8" AMOLED)</Pantalla>
        <Resolucino_Pantalla>2436x1125 pixeles</Resolucino_Pantalla>
        <Camara>7 MP</Camara>
        <Precio>1150-1350 euros</Precio>
    </Movil>
       <Movil marca="Samsung" modelo="Galaxy S9" fechaSalida="2018">
        <Procesador>Samsung Exynos 9810</Procesador>
        <Memoria_Ram>4 GB </Memoria_Ram>
        <Memoria_interna> 64/128/256 GB</Memoria_interna>
        <Bateria>3.000 mAh</Bateria>
        <Pantalla>5,8" Super AMOLED)</Pantalla>
        <Resolucino_Pantalla>2690x1440 pixeles</Resolucino_Pantalla>
        <Camara>12 MP</Camara>
        <Precio>846 euros</Precio>

    </Movil>
        <Movil marca="Huawei" modelo="P20" fechaSalida="2018">
        <Procesador>HiSilicon Kirin 970</Procesador>
        <Memoria_Ram>4 GB </Memoria_Ram>
        <Memoria_interna>128 GB</Memoria_interna>
        <Bateria>3.400 mAh</Bateria>
        <Pantalla>5,8" IPS)</Pantalla>
        <Resolucino_Pantalla> 2244x1080 p√≠xeles</Resolucino_Pantalla>
        <Camara>24 MP</Camara>
        <Precio>550 euro</Precio>

    </Movil>
</Moviles>
